export const DEFAULT_DOMAIN_SYMBOL = "diamond";

export const DOMAIN_SYMBOL_KEYS = [
  "briefcase", "building", "laptop", "code", "trending-up", "handshake", "target",
  "hammer", "factory", "store", "presentation", "package", "scale", "stethoscope",
  "wallet", "landmark", "chart", "analytics", "receipt", "heart-pulse", "activity",
  "dumbbell", "person-standing", "salad", "moon", "bike", "footprints", "cross",
  "heart-handshake", "baby", "gem", "paw-print", "dog", "house", "broom", "wrench",
  "sprout", "shopping", "utensils", "car", "hand-heart", "church", "flame", "compass",
  "shield", "anchor", "book-open", "graduation-cap", "brain", "microscope", "languages",
  "palette", "pen-line", "music", "guitar", "camera", "clapperboard", "scissors", "globe",
  "party-popper", "vote", "university", "plane", "mountain", "tent", "tree", "leaf",
  "waves", "sun", "cloud-sun", "gamepad", "chess-knight", "trophy", "coffee", "diamond",
  "circle-dot", "star", "sparkles", "shapes", "flower", "plus",
] as const;

export type DomainSymbolKey = (typeof DOMAIN_SYMBOL_KEYS)[number];

const VALID_KEYS = new Set<string>(DOMAIN_SYMBOL_KEYS);

export const LEGACY_DOMAIN_SYMBOLS: Record<string, DomainSymbolKey> = {
  "💼": "briefcase",
  "🏢": "building",
  "💻": "laptop",
  "📈": "trending-up",
  "🤝": "handshake",
  "🎯": "target",
  "🛠️": "hammer",
  "🛠": "hammer",
  "⚖️": "scale",
  "⚖": "scale",
  "🩺": "stethoscope",
  "🎓": "graduation-cap",
  "💰": "wallet",
  "💵": "wallet",
  "🏦": "landmark",
  "📊": "chart",
  "🧾": "receipt",
  "❤️": "heart-pulse",
  "❤": "heart-pulse",
  "🏃": "activity",
  "🏋️": "dumbbell",
  "🏋": "dumbbell",
  "🧘": "person-standing",
  "🥗": "salad",
  "😴": "moon",
  "🩹": "cross",
  "🚴": "bike",
  "👪": "heart-handshake",
  "👶": "baby",
  "🧑‍🤝‍🧑": "heart-handshake",
  "💍": "gem",
  "🐾": "paw-print",
  "🏡": "house",
  "🏠": "house",
  "🧹": "broom",
  "🔧": "wrench",
  "🌱": "sprout",
  "🚗": "car",
  "🙏": "hand-heart",
  "✝️": "church",
  "✝": "church",
  "⛪": "church",
  "🕯️": "flame",
  "🕯": "flame",
  "🧭": "compass",
  "📚": "book-open",
  "✍️": "pen-line",
  "✍": "pen-line",
  "🧠": "brain",
  "🎨": "palette",
  "🎵": "music",
  "🎸": "guitar",
  "📷": "camera",
  "🎬": "clapperboard",
  "🌍": "globe",
  "🎉": "party-popper",
  "🗳️": "vote",
  "🗳": "vote",
  "🏛️": "university",
  "🏛": "university",
  "✈️": "plane",
  "✈": "plane",
  "🏔️": "mountain",
  "🏔": "mountain",
  "⛺": "tent",
  "🎮": "gamepad",
  "♟️": "chess-knight",
  "♟": "chess-knight",
  "⚽": "trophy",
  "➕": "plus",
  "◇": DEFAULT_DOMAIN_SYMBOL,
  "◆": DEFAULT_DOMAIN_SYMBOL,
};

export function normalizeDomainSymbol(value: string | null | undefined): DomainSymbolKey {
  if (!value) return DEFAULT_DOMAIN_SYMBOL;
  if (VALID_KEYS.has(value)) return value as DomainSymbolKey;
  return LEGACY_DOMAIN_SYMBOLS[value] ?? DEFAULT_DOMAIN_SYMBOL;
}
