-- Email → task. Each user gets a unique forwarding address
-- `<inbound_token>@<mail-domain>`; Resend receives at the domain (catch-all) and
-- webhooks the `inbound-email` edge function, which maps the recipient's local
-- part back to this token → the user → a new inbox capture.

-- The opaque local part. 12 hex chars (48 bits) — unguessable enough for a
-- semi-public forwarding address, short enough to type. Generated by default so
-- the new-user trigger (which inserts only user_id) gets one for free.
alter table public.user_settings
  add column inbound_token text unique
  default substr(replace(gen_random_uuid()::text, '-', ''), 1, 12);

-- Backfill the existing single-user row (default only applies to new inserts).
update public.user_settings
  set inbound_token = substr(replace(gen_random_uuid()::text, '-', ''), 1, 12)
  where inbound_token is null;

alter table public.user_settings
  alter column inbound_token set not null;

-- Idempotency + audit ledger: one row per email Resend delivers to us, keyed by
-- Resend's stable `email_id`. The webhook checks this first so a Svix retry can't
-- create a duplicate task, and it doubles as a "what came in" history.
create table public.inbound_emails (
  email_id     text primary key,          -- Resend data.email_id
  user_id      uuid not null references auth.users(id) on delete cascade,
  task_id      uuid references public.tasks(id) on delete set null,
  from_address text,
  subject      text,
  received_at  timestamptz not null default now()
);

create index inbound_emails_user_idx on public.inbound_emails (user_id, received_at desc);

alter table public.inbound_emails enable row level security;

-- Read-only for the owner (history UI); all writes are service-role (the edge
-- function bypasses RLS), so no insert/update policy is granted.
create policy "read own inbound_emails" on public.inbound_emails
  for select using (auth.uid() = user_id);
