// Commands exposed to JS as `plugin:nuvo-siwa|<name>`. This list is also what
// generates permissions/autogenerated/ — plugin commands ARE permission-gated
// in Tauri v2 (app-level commands are not), so a command missing from here is
// a "Permission not found" at startup, not a compile error.
//
// `ios_path` is what makes cargo compile ios/ as a SwiftPM package and link it
// into libapp.a.
const COMMANDS: &[&str] = &["sign_in"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
